#!/bin/sh
# 
# Some aliases make use of variables kept in the file 'private' (untracked)
###############


# local machines
alias ghanima="ssh '$GHANIMA'"
alias atreides="ssh '$ATREIDES'"
alias alia="ssh '$ALIA'"
alias leto="ssh '$LETO'"

# configs
alias zshconfig="nano ~/.zshrc"
alias aliasconfig="nano ~/.alias"
alias motd="run-parts /etc/update-motd.d"
alias source-zsh="source ~/.zshrc"
